// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/prediction-cards/AsymmetricCrest.tsx": () => import("../components/mockups/prediction-cards/AsymmetricCrest.tsx"),
  "./components/mockups/prediction-cards/VersusStrip.tsx": () => import("../components/mockups/prediction-cards/VersusStrip.tsx")
};
